### Create Student
POST http://localhost:3000/api/student HTTP/1.1
content-type: application/json

{
    "title": "MR",
    "firstName": "Akshar",
    "middleName": "Bhai",
    "lastName": "Patel",
    "spuId": "180410107061",
    "batch" : "2018-2019",
    "course": "Bachelor of Architecture",
    "nationality": "Indian",
    "address": "Ur Heart",
    "dob": "2021-06-02T13:16:38.371Z"
}

### Search for a student using spuId
GET http://localhost:3000/api/student/180410107098

### Get all Students
GET http://localhost:3000/api/student?all=true