POST http://localhost:3000/api/subject
content-type: application/json

{
    "subCode": "3101165",
    "subName": "Learn how to react in React",
    "sem": "4",
    "course": "Bachelor of Architecture",
    "batch": "2018-2019"
}

###

GET http://localhost:3000/api/subject
content-type: application/json

{
    "sem": "4",
    "spuId": "180410107098"
}

###

GET http://localhost:3000/api/subject
content-type: application/json

{
    "sem": "1",
    "course": "Bachelor of Architecture",
    "batch": "2018-2019"
}